name: Build and deploy .NET Core application to Web App nikx-bits-app
on:
  push:
    branches:
    - main
  workflow_dispatch:
env:
  DOTNET_CORE_VERSION: 7.0.x
  SONAR_HOST_URL: http://nikxsonar.zapto.org:9000
  SONAR_TOKEN: sqp_e2915611209113bae2fe69f727d4f651302e97d8
  AZURE_WEBAPP_NAME: nikx-bits-app
  AZURE_WEBAPP_PACKAGE_PATH: '.'
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 
    - name: Setup .NET SDK for BITS.DevOps.Service
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Restore Dotnet Packages
      run: dotnet restore
    - name: Build BITS.DevOps.Service
      run: dotnet build --configuration Release
  test:
    runs-on: self-hosted
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
      - name: Restore Dotnet Packages
        run: dotnet restore
      - name: Test Project
        run: dotnet test BITS.DevOps.Service.Tests/BITS.DevOps.Service.Tests.csproj /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=json
  sonar_analysis:
    runs-on: self-hosted
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
      - name: Restore Dotnet Packages
        run: dotnet restore
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17          
      - name: Build and analyze
        run: |
          dotnet sonarscanner begin /k:"NikxBitsDevOpsAssignment" /d:sonar.host.url="${{ env.SONAR_HOST_URL }}"  /d:sonar.token="${{ env.SONAR_TOKEN }}" /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml
          dotnet build
          dotnet-coverage collect "dotnet test" -f xml -o "coverage.xml"
          dotnet-sonarscanner end /d:sonar.token="${{ env.SONAR_TOKEN }}"
  deploy:
    runs-on: self-hosted
    needs: sonar_analysis
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
      - name: Build with dotnet
        run: dotnet build --configuration Release
      - name: dotnet publish
        run: dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'nikx-bits-app'
          slot-name: 'Production'
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_67CEE8DAC5FC498482ED3255294CB566 }}
      
    